version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=sudoku
      - QUEUE_NAME=sudoku_tasks
    volumes:
      - ./app:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - rabbitmq
      - mysql

  worker:
    build: .
    command: python worker.py
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=sudoku
      - QUEUE_NAME=sudoku_tasks
    volumes:
      - ./app:/app
    depends_on:
      - rabbitmq
      - mysql

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sudoku
    ports:
      - "3307:3306"
    volumes:
      - ./app/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

networks:
  sudoku-network:
    driver: bridge 